name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger from Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build


    - name: Upload build artifacts
      if: matrix.node-version == '20' # Only upload from one Node.js version
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: |
          dist/
          demo.html
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: ./build

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Create Pages deployment structure
      run: |
        mkdir -p ./pages
        # Copy demo.html as index.html for GitHub Pages
        cp ./build/demo.html ./pages/index.html
        # Copy dist folder
        cp -r ./build/dist ./pages/
        # Copy README for reference
        cp README.md ./pages/
        cp README-en.md ./pages/ 2>/dev/null || true

    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./pages

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
